[project]
name = "gorilla-dbt"
version = "0.1.0"
description = "Demo of transforming Gorilla experiment data using dbt"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dbt-core>=1.10.11",
    "dbt-duckdb>=1.9.6",
]
